# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pr:
  branches:
    include:
      - main  # Trigger the pipeline on PRs targeting the 'main' branch.

trigger:
  branches:
    include:
      - main  # This triggers the pipeline on push to 'main' branch, as already defined.

pool:
  vmImage: 'ubuntu-latest'  # Use a Linux-based VM image (you can change this to 'windows-latest' or 'macos-latest' if needed)

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
    - job: BuildJob
      displayName: 'Build Job'
      steps:
        - checkout: self

        - task: NodeTool@0
          inputs:
            versionSpec: '16.x'  # Specify the version of Node.js (you can change this as needed)
          displayName: 'Install Node.js'

        - task: npm@1
          inputs:
            command: 'install'  # Install dependencies from package.json
          displayName: 'Install dependencies'

        - task: XplatGenerateReleaseNotes@4
          displayName: 'Generate Release Notes'
          inputs:
            outputfile: '$(Build.ArtifactStagingDirectory)/releasenotes.md'  # Path to output the release notes file
            templateLocation: 'inline'  # Use an inline template for generating the release notes
            inlinetemplate: |
              ## Build {{buildDetails.buildNumber}}
              ## Release {{releaseDetails.releaseNumber}}

              # Global list of Changes
              ## Core Changes
              
              {{#forEach this.workItems}}
              {{#if isFirst}} #### Features 
              {{/if}}
              {{#if (and (contains (lookup this.fields 'System.Tags') 'RN-Core') (contains (lookup this.fields 'System.Tags') 'RN-Feature'))}}
              *  **{{lookup this.fields 'System.Title'}}**  {{{lookup this.fields 'System.Description'}}}
              {{/if}}
              {{/forEach}}

              {{#forEach this.workItems}}
              {{#if isFirst}} #### Enhancements
              {{/if}}
              {{#if (and (contains (lookup this.fields 'System.Tags') 'RN-Core') (contains (lookup this.fields 'System.Tags') 'RN-Enhancement'))}}
              *  **{{lookup this.fields 'System.Title'}}**  {{{lookup this.fields 'System.Description'}}}
              {{/if}}
              {{/forEach}}

              {{#forEach this.workItems}}
              {{#if isFirst}} #### Bug Fixes 
              {{/if}}
              {{#if (and (contains (lookup this.fields 'System.Tags') 'RN-Core') (contains (lookup this.fields 'System.Tags') 'RN-Bugfix'))}}
              *  **{{lookup this.fields 'System.Title'}}**  {{{lookup this.fields 'System.Description'}}}
              {{/if}}   
              {{/forEach}}

              ## Conduit Changes
              
              {{#forEach this.workItems}}
              {{#if isFirst}} #### Features 
              {{/if}}
              {{#if (and (contains (lookup this.fields 'System.Tags') 'RN-Conduit') (contains (lookup this.fields 'System.Tags') 'RN-Feature'))}}
              *  **{{lookup this.fields 'System.Title'}}**  {{{lookup this.fields 'System.Description'}}}
              {{/if}}
              {{/forEach}}

              {{#forEach this.workItems}}
              {{#if isFirst}} #### Enhancements
              {{/if}}
              {{#if (and (contains (lookup this.fields 'System.Tags') 'RN-Conduit') (contains (lookup this.fields 'System.Tags') 'RN-Enhancement'))}}
              *  **{{lookup this.fields 'System.Title'}}**  {{{lookup this.fields 'System.Description'}}}
              {{/if}}
              {{/forEach}}

              {{#forEach this.workItems}}
              {{#if isFirst}} #### Bug Fixes 
              {{/if}}
              {{#if (and (contains (lookup this.fields 'System.Tags') 'RN-Conduit') (contains (lookup this.fields 'System.Tags') 'RN-Bugfix'))}}
              *  **{{lookup this.fields 'System.Title'}}**  {{{lookup this.fields 'System.Description'}}}
              {{/if}}   
              {{/forEach}}

              ## Inigo Changes
              
              {{#forEach this.workItems}}
              {{#if isFirst}} #### Features 
              {{/if}}
              {{#if (and (contains (lookup this.fields 'System.Tags') 'RN-Inigo') (contains (lookup this.fields 'System.Tags') 'RN-Feature'))}}
              *  **{{lookup this.fields 'System.Title'}}**  {{{lookup this.fields 'System.Description'}}}
              {{/if}}
              {{/forEach}}

              {{#forEach this.workItems}}
              {{#if isFirst}} #### Enhancements
              {{/if}}
              {{#if (and (contains (lookup this.fields 'System.Tags') 'RN-Inigo') (contains (lookup this.fields 'System.Tags') 'RN-Enhancement'))}}
              *  **{{lookup this.fields 'System.Title'}}**  {{{lookup this.fields 'System.Description'}}}
              {{/if}}
              {{/forEach}}

              {{#forEach this.workItems}}
              {{#if isFirst}} #### Bug Fixes 
              {{/if}}
              {{#if (and (contains (lookup this.fields 'System.Tags') 'RN-Inigo') (contains (lookup this.fields 'System.Tags') 'RN-Bugfix'))}}
              *  **{{lookup this.fields 'System.Title'}}**  {{{lookup this.fields 'System.Description'}}}
              {{/if}}   
              {{/forEach}}

              ## Tamesis Changes
              
              {{#forEach this.workItems}}
              {{#if isFirst}} #### Features 
              {{/if}}
              {{#if (and (contains (lookup this.fields 'System.Tags') 'RN-Tamesis') (contains (lookup this.fields 'System.Tags') 'RN-Feature'))}}
              *  **{{lookup this.fields 'System.Title'}}**  {{{lookup this.fields 'System.Description'}}}
              {{/if}}
              {{/forEach}}

              {{#forEach this.workItems}}
              {{#if isFirst}} #### Enhancements
              {{/if}}
              {{#if (and (contains (lookup this.fields 'System.Tags') 'RN-Tamesis') (contains (lookup this.fields 'System.Tags') 'RN-Enhancement'))}}
              *  **{{lookup this.fields 'System.Title'}}**  {{{lookup this.fields 'System.Description'}}}
              {{/if}}
              {{/forEach}}

              {{#forEach this.workItems}}
              {{#if isFirst}} #### Bug Fixes 
              {{/if}}
              {{#if (and (contains (lookup this.fields 'System.Tags') 'RN-Tamesis') (contains (lookup this.fields 'System.Tags') 'RN-Bugfix'))}}
              *  **{{lookup this.fields 'System.Title'}}**  {{{lookup this.fields 'System.Description'}}}
              {{/if}}   
              {{/forEach}}

        - publish: $(Build.ArtifactStagingDirectory)/releasenotes.md  # Publish the release notes as an artifact
          artifact: releaseNotes
          displayName: 'Publish Release Notes Artifact'

        # Add other build tasks like linting, building, and testing here
        - task: npm@1
          inputs:
            command: 'custom'  # Run tests (adjust this based on your project)
            customCommand: 'test'
          displayName: 'Run Tests'

- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Build
  jobs:
    - job: DeployJob
      displayName: 'Deploy Job'
      steps:
        - download: current  # Download artifacts from the Build stage
          artifact: releaseNotes
          displayName: 'Download Release Notes Artifact'

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact'
          inputs:
            artifactName: 'releaseNotes'
            targetPath: '$(Pipeline.Workspace)/releaseNotes'

